version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  
conda:
  environment: docs/environment.yaml
  
sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
